### ISSUE TITLE
Enrich author markup

### ISSUE THREAD

**Issue by cmil** [dracor-org/amdracor#4]
Currently (as of #3 that is) the content of the `author` elements is just plain text. We should properly encode the forename, surname and possible other name parts to unlock API feature relying on that markup. See https://dracor.org/doc/odd#TEI.author.

**Comment by lucagiovannini7** [comment]
The issue should have been solved by [this commit](https://github.com/dracor-org/amdracor/commit/c8ccbb662f2cdae2e9dc1317957fce6668968519) (I refactored the `author` element and manually added Wikidata/GND).
